name = "hugo-emaillist-theme"
license = "MIT"
licenselink = "https://github.com/tvmaly/hugo-emaillist-theme/blob/master/LICENSE.md"
description = "A theme with landing page focused on a call to action to signup on an email newsletter"
homepage = "https://github.com/tvmaly/hugo-emaillist-theme/"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 0.19

[author]
  name = "Tyson Maly"
  homepage = "https://github.com/tvmaly"
